### ISSUE TITLE
Map DataType fields are not populated with inherited values

### ISSUE THREAD

**Issue by gianluca-piccolo-wuerth** [nbuchwitz/icingaweb2-module-mapDatatype#3]
Inherited coordinates are not shown in hosts and templates form geolocation fields. 

## Expected Behavior
If I have a host or a host template that inherits another template with coordinates value, in the form I would like to see the inherited value. 

## Current Behavior
The inherited value for the coordinates field (geolocation) is not shown.

## Possible Solution
Set the placeholder of the element as the other element of the director host objects forms (I think this means also make some changes in the director code) or set a custom placeholder attribute to the map datatype element and add it to the element view (location.phtml).

## Steps to Reproduce (for bugs)
1. Create a custom Location (MapDatatype) field.
2. Create a template.
3. Assign to it the Location custom field (custom var).
4. Select a location for the template.
5. Add a new host that inherits the template with location field.
6. Take a look at the location field in the host object form. It will be empty also if in the resolved object preview the location field is not (inherited from template).

## Your Environment

* Icinga Web 2 MapDatatype version (System - About): 0.0.1
* Icinga Web 2 Map version (System - About): We don't use Icinga Web 2 Map module
* Icinga Web 2 Director version (System - About): 1.5.1
* Icinga Web 2 version and modules (System - About): 2.6.1
* Version used (`icinga2 --version`): 2.8.4
* Operating System and version: CentOS 7
* Enabled features (`icinga2 feature list`): api checker ido-mysql influxdb livestatus mainlog
* Config validation (`icinga2 daemon -C`): OK

**Comment by nbuchwitz** [comment]
Thanks for reporting. I added the missing placeholder value to the view helper.

Please test again with current GIT master.
